trigger:
  branches:
    include: ['master']

variables:
  # Agent VM image name
  vmImageName: 'vs2017-win2016'

stages:
- stage: Build
  jobs:
  - job:
    pool:
      vmImage: $(vmImageName)

    variables:
      solution: '*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

    steps:
    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
        maximumCpuCount: true
        msbuildArgs: /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal

    # Publish all needed files for the Release pipeline
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: |
          Overview.md
          build/**
          VS2019/**/*.vsix
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'drop'
        targetPath: '$(Build.ArtifactStagingDirectory)'


- stage: Publish
  displayName: Deploy stage
  dependsOn: Build
  condition: and(succeeded(),startsWith(variables['Build.SourceBranch'], 'refs/heads/'))
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'development'
    pool:
      vmImage: $(vmImageName)

    strategy:
      runOnce:
        deploy:

          steps:
          - task: PublishAzureDevOpsExtension@3
            inputs:
              connectTo: 'VsTeam'
              connectedServiceName: 'Visual Studio Marketplace'
              fileType: 'vsix'
              vsixFile: '$(Pipeline.Workspace)/drop/*.vsix'
              updateTasksVersion: false
              extensionVisibility: 'public'
              extensionPricing: 'free'
