trigger:
  branches:
    include: ['master']

variables:
  # Agent VM image name
  vmImageName: 'vs2017-win2016'
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages

stages:
- stage: Build
  jobs:
  - job:
    pool:
      vmImage: $(vmImageName)

    variables:
      solution: '*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

    steps:
    - task: Cache@2
      inputs:
        key: 'nuget | "$(Agent.OS)" | **/packages.lock.json,!**/bin/**'
        restoreKeys: |
          nuget | "$(Agent.OS)"
        path: $(NUGET_PACKAGES)
      displayName: Cache NuGet packages

    - task: NuGetToolInstaller@1
      inputs:
        versionSpec: '5.6.0'

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
        maximumCpuCount: true
        msbuildArgs: /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal

    # Publish all needed files for the Release pipeline
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: |
          Overview.md
          build/**
          VS2019/**/*.vsix
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'drop'
        targetPath: '$(Build.ArtifactStagingDirectory)'

- stage: Publish
  displayName: Deploy stage
  dependsOn: Build
  condition: and(succeeded(),startsWith(variables['Build.SourceBranch'], 'refs/heads/'))
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'Visual Studio Marketplace'
    pool:
      vmImage: $(vmImageName)

    strategy:
      runOnce:
        deploy:
          steps:

          - task: PublishVisualStudioExtension@3
            inputs:
              connectedServiceName: 'Visual Studio Marketplace'
              vsixFile: '$(Pipeline.Workspace)/drop/VS2019/bin/Release/Gardiner.VsShowMissing.VS2019.vsix'
              manifestFile: '$(Pipeline.Workspace)/drop/build/extension-manifest.json'
              publisherId: 'DavidGardiner'
              ignoreWarnings: 'VSIXValidatorWarning01,VSIXValidatorWarning02,VSIXValidatorWarning08'