// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.9.178
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DavidGardiner.Gardiner_VsShowMissing
{
    static class Vsix
    {
        public const string Id = "36b8e40e-ceaa-4305-bdb7-1a68a0d84067";
        public const string Name = "Show Missing Files";
        public const string Description = @"Find files references in project files that don't exist on disk, and optionally files that do exist on disk that aren't included in a project. 
Runs on Build. Missing files are listed in Error List window.";
        public const string Language = "en-US";
        public const string Version = "2.1.1";
        public const string Author = "David Gardiner";
        public const string Tags = "Missing, Warnings";
    }
}
