// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Gardiner.VsShowMissing
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string VS2022String = "c321819f-bf99-4323-b9fc-366754457ae9";
        public static Guid VS2022 = new Guid(VS2022String);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyErrorListMenuGroup = 0x0002;
        public const int cmdidDeleteFileOnDisk = 0x0200;
        public const int cmdidIncludeFileInProject = 0x0201;
        public const int cmdidExcludeFileFromProject = 0x0202;
    }
}