// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DavidGardiner.Gardiner_VsShowMissing
{
    internal sealed partial class Vsix
    {
        public const string Id = "VS2019.52b01d49-2718-47a2-a08f-117f19edf495";
        public const string Name = "Show Missing Files";
        public const string Description = @"Find files references in project files that don't exist on disk, and optionally files that do exist on disk that aren't included in a project. 
Runs on Build. Missing files are listed in Error List window.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "David Gardiner";
        public const string Tags = "Missing, Warnings";
    }
}
