// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Gardiner.VsShowMissing
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVsShowMissingPackageString = "854a65d3-44ed-49e8-911c-8fd46150b53b";
        public static Guid guidVsShowMissingPackage = new Guid(guidVsShowMissingPackageString);

        public const string guidVsShowMissingPackageCmdSetString = "5296bc5d-d49b-4ce9-908e-c4c7947459be";
        public static Guid guidVsShowMissingPackageCmdSet = new Guid(guidVsShowMissingPackageCmdSetString);

        public const string guidGardiner_ErrorListCmdSetString = "a4d9c40f-e108-425c-8c72-9f99c53e3643";
        public static Guid guidGardiner_ErrorListCmdSet = new Guid(guidGardiner_ErrorListCmdSetString);

        public const string guidImagesString = "4e99792d-a2b9-4f78-99cf-97b95335914e";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int cmdidFindMissingFiles = 0x0100;
        public const int MyErrorListMenuGroup = 0x1021;
        public const int cmdidDeleteFileOnDisk = 0x0200;
        public const int cmdidIncludeFileInProject = 0x0201;
        public const int cmdidExcludeFileFromProject = 0x0202;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}